// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2ioCzSEavd48f-O4IHfaibvzZL_eWK9A',
    appId: '1:556022123095:web:5e55d83de651479d6df112',
    messagingSenderId: '556022123095',
    projectId: 'plasto-28580',
    authDomain: 'plasto-28580.firebaseapp.com',
    storageBucket: 'plasto-28580.firebasestorage.app',
    measurementId: 'G-0314R66HZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfE2t4cEsBx3tkO0lSUfECzUFsrLHJoX4',
    appId: '1:556022123095:android:b2a368177bdbef2b6df112',
    messagingSenderId: '556022123095',
    projectId: 'plasto-28580',
    storageBucket: 'plasto-28580.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDORabsDip6utO_PN6-zx3T3f3-jTBnKvY',
    appId: '1:556022123095:ios:14c7d150b65263e66df112',
    messagingSenderId: '556022123095',
    projectId: 'plasto-28580',
    storageBucket: 'plasto-28580.firebasestorage.app',
    iosBundleId: 'com.example.greenearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDORabsDip6utO_PN6-zx3T3f3-jTBnKvY',
    appId: '1:556022123095:ios:14c7d150b65263e66df112',
    messagingSenderId: '556022123095',
    projectId: 'plasto-28580',
    storageBucket: 'plasto-28580.firebasestorage.app',
    iosBundleId: 'com.example.greenearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2ioCzSEavd48f-O4IHfaibvzZL_eWK9A',
    appId: '1:556022123095:web:1fc1530469515c5c6df112',
    messagingSenderId: '556022123095',
    projectId: 'plasto-28580',
    authDomain: 'plasto-28580.firebaseapp.com',
    storageBucket: 'plasto-28580.firebasestorage.app',
    measurementId: 'G-Z47PBDXFSG',
  );
}
